SELECT 
C_17.YEAR,
C_17.PROJECT_CODE,
C_17.EVENT_ID,
C_17.STATION_ID,
MT10_T as Pre4, 
MT9_T as Pre3,
MT8_T + MT7_T as Pre2,
MT6_T + MT5_T as Pre1, 
MT1_T + MT2_T + MT3_T + MT4_T as Legal,
TM_T as TotMales,
FT11_T as JuvFems,
FT12_T + FT13_T as MatFems,
TF_T as TotFems
FROM C_17
 INNER JOIN DATA_EVENTS ON C_17.EVENT_ID = DATA_EVENTS.EVENT_ID
	WHERE (((DATA_EVENTS.GEAR_PERFORMANCE_CODE)="01") AND C_17.YEAR = '2017' AND C_17.PROJECT_CODE = 'T04');
